from pydantic import BaseModel, Field
from typing import List, Optional

class ActionItem(BaseModel):
    """Represents a single task assigned during a meeting."""
    task: str = Field(..., description="The specific task that needs to be completed.")
    assignee: Optional[str] = Field(None, description="The name of the person assigned to the task. Null if unassigned.")
    due_date: Optional[str] = Field(None, description="The deadline for the task, if mentioned (e.g., 'Next Friday', 'Oct 12th').")
    priority: str = Field(
        default="Normal", 
        description="Priority level of the task: High, Normal, or Low."
    )

class MeetingSummary(BaseModel):
    """The final structured output generated by the LLM after analyzing a transcript."""
    executive_summary: str = Field(
        ..., 
        description="A concise 2-3 paragraph summary of the entire meeting."
    )
    key_decisions: List[str] = Field(
        ..., 
        description="A bulleted list of the major decisions agreed upon during the call."
    )
    action_items: List[ActionItem] = Field(
        ..., 
        description="A list of all action items extracted from the meeting."
    )
    overall_sentiment: str = Field(
        ..., 
        description="The overall emotional tone of the meeting (e.g., Positive, Neutral, Tense, Collaborative)."
    )

class TranscriptionResponse(BaseModel):
    """The output format after processing the raw audio through Whisper."""
    filename: str
    transcript_text: str
    duration_seconds: float